import "./globals.css";
import { Playfair_Display, Inter } from 'next/font/google';

// হেডিং এর জন্য সেরিফ ফন্ট
const playfair = Playfair_Display({
  subsets: ['latin'],
  variable: '--font-playfair', // CSS ভ্যারিয়েবল হিসেবে ব্যবহারের জন্য
  weight: ['700', '900'],
});

// বডি টেক্সট এর জন্য সান-সেরিফ ফন্ট
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  weight: ['400', '500', '600'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${inter.variable} ${playfair.variable} font-sans bg-[#F9F8F6]`}>
        {children}
      </body>
    </html>
  );
}